#!/bin/sh
#
# MIT License
#
# Copyright (c) 2018-2019 Ingo Theiss <ingo.theiss@i-matrixx.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Source common definitions
. $(dirname $0)/common

### Install port config
${BIN_SERVICETOOL} --install-configure-file --package ${PACKAGE_TARGET_LOCATION}/etc/openHAB.sc

### Create share for openHAB

# Absolute path of the share
openhab_synoshare="$(${BIN_SERVICETOOL} --get-alive-volume)/${PACKAGE_NAME}"

# Check if share exists
${BIN_SYNOSHARE} --get "${PACKAGE_NAME}" 2>&1 >/dev/null
if [[ $? != 0 ]]
then
    # Create share
    ${BIN_SYNOSHARE} --add "${PACKAGE_NAME}" "" "${openhab_synoshare}" "" "" "" 0 0
    if [[ $? != 0 ]]
    then
        logger -p 0 "${PACKAGE_NAME}_${SCRIPT_NAME}: failed to create ${PACKAGE_NAME} share"
        echo "Failed to create openHAB share!" > ${SYNOPKG_TEMP_LOGFILE}
        exit 1
    fi

    # Add permissions
    ${BIN_SYNOSHARE} --setuser ${PACKAGE_NAME} RW + ${PACKAGE_NAME},@administrators
    if [[ $? != 0 ]]
    then
        logger -p 0 "${PACKAGE_NAME}_${SCRIPT_NAME}: failed to add permissions for openHAB share."
        echo "Failed to add permissions for openHAB share!" > ${SYNOPKG_TEMP_LOGFILE}
	exit 2
    fi	    
fi

### Copy and link file to openHAB share

# Copy and link addons directory
if [[ -d ${openhab_synoshare}/addons ]]
then
    ${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/addons
else
    ${BIN_MV} ${PACKAGE_TARGET_LOCATION}/src/addons ${openhab_synoshare}/
fi

${BIN_LN} -sf ${openhab_synoshare}/addons ${PACKAGE_TARGET_LOCATION}/src/addons

# Copy and link conf directory
if [[ -d ${openhab_synoshare}/conf ]]
then
    ${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/conf
else
    ${BIN_MV} ${PACKAGE_TARGET_LOCATION}/src/conf ${openhab_synoshare}/
fi

${BIN_LN} -sf ${openhab_synoshare}/conf ${PACKAGE_TARGET_LOCATION}/src/conf

# Create and link logs directory
if [[ -d ${openhab_synoshare}/logs ]]
then
    ${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/userdata/logs
else
    ${BIN_MKDIR} ${openhab_synoshare}/logs
    ${BIN_CHMOD} 775 ${openhab_synoshare}/logs
    ${BIN_CHOWN} ${PACKAGE_NAME}:${PACKAGE_NAME} ${openhab_synoshare}/logs
fi

${BIN_LN} -sf ${openhab_synoshare}/logs ${PACKAGE_TARGET_LOCATION}/src/userdata/logs

# Set openHAB environment from package-wizard
if [[ "${SYNOPKG_PKG_STATUS}" == "INSTALL" ]]
then
    printf 'export OPENHAB_HTTP_PORT="%s"\n' "${pkgwizard_http_port:-${DEFAULT_OPENHAB_HTTP_PORT}}" > ${OPENHAB_SYNOLOGY_ENV}
    printf 'export OPENHAB_HTTPS_PORT="%s"\n' "${pkgwizard_https_port:-${DEFAULT_OPENHAB_HTTPS_PORT}}" >> ${OPENHAB_SYNOLOGY_ENV}
    printf 'export OPENHAB_HTTP_ADDRESS="%s"\n' "${pkgwizard_inet_addr:-${DEFAULT_OPENHAB_HTTP_ADDRESS}}" >> ${OPENHAB_SYNOLOGY_ENV}
    printf 'export JAVA_OPTS="${JAVA_OPTS_TRUSTSTORE}"' >> ${OPENHAB_SYNOLOGY_ENV}

    ${BIN_CHMOD} 644 ${OPENHAB_SYNOLOGY_ENV}
    ${BIN_CHOWN} ${PACKAGE_NAME}:${PACKAGE_NAME} ${OPENHAB_SYNOLOGY_ENV}

    # Change adminport inside INFO
    sed -i "s|adminport=\"\([0-9]*\)\"|adminport=\"${pkgwizard_https_port}\"|g" ${PACKAGE_LOCATION}/INFO
fi

### Import Synology certificates into openHAB keystore

create_cert_keystore

exit 0
