#!/bin/sh
#
# MIT License
#
# Copyright (c) 2017 Ingo Theiss <ingo.theiss@i-matrixx.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Source common definitions
. $(dirname $0)/common

### Create share for openHAB

# Absolute path of the share
openhab_synoshare="$(${BIN_SERVICETOOL} --get-first-alive-volume)/${PACKAGE_NAME}"

# Create share
${BIN_SYNOSHARE} --get "${PACKAGE_NAME}"
if [ $? -ne 0 ]
then
    ${BIN_SYNOSHARE} --add "${PACKAGE_NAME}" "" "${openhab_synoshare}" "" "" "" 0 0
    if [ $? -ne 0 ]
    then
        logger -p 0 "${PACKAGE_NAME}: failed to create ${PACKAGE_NAME} share"
        exit 1
    fi
fi

# Add permissions
${BIN_SYNOSHARE} --setuser ${PACKAGE_NAME} RW + ${PACKAGE_NAME},@administrators

### Copy and link file to openHAB share

# Copy and link addons directory
if [ -d ${openhab_synoshare}/addons ]
then
    ${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/addons
else
    ${BIN_MV} ${PACKAGE_TARGET_LOCATION}/src/addons ${openhab_synoshare}/
fi

${BIN_LN} -sf  ${openhab_synoshare}/addons ${PACKAGE_TARGET_LOCATION}/src/addons

# Copy and link conf directory
if [ -d ${openhab_synoshare}/logs ]
then
    ${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/userdata/logs
else
    ${BIN_MV} ${PACKAGE_TARGET_LOCATION}/src/userdata/logs ${openhab_synoshare}/
fi

${BIN_LN} -sf  ${openhab_synoshare}/logs ${PACKAGE_TARGET_LOCATION}/src/userdata/logs

# Copy and link logs directory
if [ -d ${openhab_synoshare}/conf ]
then
    ${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/conf
else
    ${BIN_MV} ${PACKAGE_TARGET_LOCATION}/src/conf ${openhab_synoshare}/
fi

${BIN_LN} -sf  ${openhab_synoshare}/conf ${PACKAGE_TARGET_LOCATION}/src/conf

# Set openHAB environment from package-wizard
if [ "${SYNOPKG_PKG_STATUS}" == "INSTALL" ]
then
    printf 'export OPENHAB_HTTP_PORT="%s"\n' "${pkgwizard_http_port}" > ${OPENHAB_SYNOLOGY_ENV}
    printf 'export OPENHAB_HTTPS_PORT="%s"\n' "${pkgwizard_https_port}" >> ${OPENHAB_SYNOLOGY_ENV}

    ${BIN_CHMOD} 644 ${OPENHAB_SYNOLOGY_ENV}
    ${BIN_CHOWN} ${PACKAGE_NAME}:${PACKAGE_NAME} ${OPENHAB_SYNOLOGY_ENV}

    # Change adminport inside INFO
    sed -i "s|adminport=\"\([0-9]*\)\"|adminport=\"${pkgwizard_https_port}\"|g" ${PACKAGE_LOCATION}/INFO

    if [ "${pkgwizard_force_inet_addr}" == "true" ]
    then
        # Persist network address from wizard
        grep -Fq "org.eclipse.smarthome.network:primaryAddress" ${PACKAGE_TARGET_LOCATION}/src/conf/services/runtime.cfg

        if [ $? -eq 0 ]
        then
            # Replace value with new value from wizard
	    sed -i "s|org.eclipse.smarthome.network:primaryAddress = \([0-9./]*\)|org.eclipse.smarthome.network:primaryAddress = ${pkgwizard_inet_addr}|g" ${PACKAGE_TARGET_LOCATION}/src/conf/services/runtime.cfg
        else
            # Insert network settings
            printf "\n################ NETWORK ####################\n\n" >> ${PACKAGE_TARGET_LOCATION}/src/conf/services/runtime.cfg
            printf "# The network address used by openHAB aka listen address\n#\n" >> ${PACKAGE_TARGET_LOCATION}/src/conf/services/runtime.cfg
            printf "org.eclipse.smarthome.network:primaryAddress = %s\n" "${pkgwizard_inet_addr}" >> ${PACKAGE_TARGET_LOCATION}/src/conf/services/runtime.cfg
        fi
    fi
fi

### Import Synology certificates into openHAB keystore

create_cert_keystore

exit 0
