#!/bin/sh
#
# MIT License
#
# Copyright (c) 2018 Ingo Theiss <ingo.theiss@i-matrixx.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Source common definitions
. $(dirname $0)/common

# Remove runtime dir
${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/runtime
# Remove userdata cache and tmp dir
${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/userdata/cache
${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/userdata/tmp

# Remove symlink for logs directory
if [ -L ${PACKAGE_TARGET_LOCATION}/src/userdata/logs ]
then
    ${BIN_RM} ${PACKAGE_TARGET_LOCATION}/src/userdata/logs
else
    ${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/userdata/logs
fi

# Remove openHAB system files which need to be replaced
if [ -f "${PACKAGE_TARGET_LOCATION}/src/runtime/bin/userdata_sysfiles.lst" ]
then
    ${BIN_CAT} ${PACKAGE_TARGET_LOCATION}/src/runtime/bin/userdata_sysfiles.lst | xargs rm -f
else
    logger -p 0 "${PACKAGE_NAME}_${SCRIPT_NAME}: The required package file >${PACKAGE_TARGET_LOCATION}/src/runtime/bin/userdata_sysfiles.lst< is not available. Upgrade failed!"
    echo "The required package file >${PACKAGE_TARGET_LOCATION}/src/runtime/bin/userdata_sysfiles.lst< is not available. Upgrade failed!" > ${SYNOPKG_TEMP_LOGFILE}
fi

# Backup openHAB userdata directory
${BIN_MV} ${PACKAGE_TARGET_LOCATION}/src/userdata ${SYNOPKG_TEMP_UPGRADE_FOLDER}/userdata

if [ $? -ne 0 ]
then
    logger -p 0 "${PACKAGE_NAME}_${SCRIPT_NAME}: failed to backup openHAB userdata!"
    echo "Failed to backup openHAB userdate directory!" > ${SYNOPKG_TEMP_LOGFILE}
    exit 1
fi

# Keep a backup in case the user modified logging configuration
${BIN_MV} ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/org.ops4j.pax.logging.cfg ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/org.ops4j.pax.logging.cfg.spk

exit 0
