#!/bin/sh
#
# MIT License
#
# Copyright (c) 2018-2019 Ingo Theiss <ingo.theiss@i-matrixx.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Source common definitions
. $(dirname $0)/common

# Remove runtime dir
${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/runtime
# Remove userdata cache and tmp dir
${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/userdata/cache
${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/userdata/tmp

# Remove symlink for logs directory
if [ -L ${PACKAGE_TARGET_LOCATION}/src/userdata/logs ]
then
    ${BIN_RM} ${PACKAGE_TARGET_LOCATION}/src/userdata/logs
else
    ${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/userdata/logs
fi

# Remove openHAB system files
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/all.policy
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/branding.properties
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/branding-ssh.properties
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/config.properties
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/custom.properties
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/custom.system.properties
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/distribution.info
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/jre.properties
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/org.apache.karaf*
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/org.ops4j.pax.url.mvn.cfg
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/profile.cfg
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/startup.properties
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/system.properties
${BIN_RM} -f ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/version.properties

# Keep a backup in case the user modified logging configuration
${BIN_MV} ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/org.ops4j.pax.logging.cfg ${PACKAGE_TARGET_LOCATION}/src/userdata/etc/org.ops4j.pax.logging.cfg.spk

# Backup openHAB userdata directory
${BIN_MV} ${PACKAGE_TARGET_LOCATION}/src/userdata ${SYNOPKG_TEMP_UPGRADE_FOLDER}/userdata
if [[ $? != 0 ]]
then
    logger -p 0 "${PACKAGE_NAME}_${SCRIPT_NAME}: failed to backup openHAB userdata!"
    echo "Failed to backup openHAB userdate directory!" > ${SYNOPKG_TEMP_LOGFILE}
    exit 1
fi

exit 0
